import { defineConfig } from "vite";
import { resolve } from "node:path";

// Jimmy's sounds live in public/sounds (generated by scripts/gen-sounds.py).
// Vite serves public/ at the site root in dev and copies it into dist/ on build,
// so they are reachable at /sounds/<name>.wav in both.

export default defineConfig({
  clearScreen: false,
  server: { port: 1420, strictPort: true, host: "127.0.0.1" },
  envPrefix: ["VITE_", "TAURI_ENV_"],
  build: {
    target: "chrome110",
    minify: "esbuild",
    sourcemap: false,
    emptyOutDir: true,
    rollupOptions: {
      input: {
        island: resolve(__dirname, "index.html"),
        settings: resolve(__dirname, "settings.html"),
      },
    },
  },
});
